- include_vars: "{{ansible_os_family}}.yml"

# User creation, server actions
- name: Create User {{item.name}}
  local_action: user name={{item.name}} password={{item.password}} generate_ssh_key=yes shell=/bin/bash
  with_items: USERS

- local_action: shell cp /home/{{item.name}}/.ssh/id_rsa.pub /tmp/{{item.name}}_id_rsa.pub creates=/tmp/{{item.name}}_id_rsa.pub
  with_items: USERS

- name: Create User {{item.name}}
  action: user name={{item.name}} password={{item.password}} shell=/bin/bash
  with_items: USERS

- name: Add the authorized_key to the user {{item.name}}
  local_action: authorized_key user={{item.name}} key="{{ lookup('file', '/tmp/' + item.name + '_id_rsa.pub') }}"
  with_items: USERS

- template: src=ssh_known_hosts.conf dest=/etc/ssh/ssh_known_hosts

- name: Add EPEL repo
  template: src=utils/templates/epel.repo dest=/etc/yum.repos.d/epel.repo
  when: "ansible_os_family == 'RedHat'"

- include: "{{torque_type_of_node}}.yml"

- name: Open ports in the firewall
  command: iptables -I INPUT -p {{item}} --dport 15001:15004 -j ACCEPT
  ignore_errors: yes
  with_items:
   - tcp
   - udp

- name: save iptables
  shell: iptables-save > /etc/sysconfig/iptables
  when: "ansible_os_family == 'RedHat'"
