- include_vars: "{{ansible_os_family}}.yml"

# User creation, server actions
- name: Create User {{item.name}}
  local_action: user name={{item.name}} password={{item.password}} generate_ssh_key=yes shell=/bin/bash
  with_items: USERS

- local_action: shell cp /home/{{item.name}}/.ssh/id_rsa.pub /tmp/{{item.name}}_id_rsa.pub creates=/tmp/{{item.name}}_id_rsa.pub
  with_items: USERS

- local_action: shell cp /home/{{item.name}}/.ssh/id_rsa /tmp/{{item.name}}_id_rsa creates=/tmp/{{item.name}}_id_rsa
  with_items: USERS

- name: Set the permissions of file /tmp/{{item.name}}_id_rsa
  local_action: file path=/tmp/{{item.name}}_id_rsa mode=0644
  with_items: USERS

# User creation, node actions
- name: Create User {{item.name}}
  action: user name={{item.name}} password={{item.password}} shell=/bin/bash
  with_items: USERS

- name: Add the authorized_key to the user {{item.name}}
  authorized_key: user={{item.name}} key="{{ lookup('file', '/tmp/' + item.name + '_id_rsa.pub') }}"
  with_items: USERS

- template: src=ssh_known_hosts.conf dest=/etc/ssh/ssh_known_hosts

- include: "{{torque_type_of_node}}.yml"


















