- include_vars: "{{ansible_os_family}}.yml"

- include: "{{torque_type_of_node}}.yml"

# Users creation
- name: Create User {{item.name}}
action: user name={{item.name}} password={{item.password}} shell=/bin/bash
with_items: USERS

- name: Add the authorized_key to the user {{item.name}}
authorized_key: user={{item.name}} key="{{ lookup('file', '/tmp/' + item.name + '_id_rsa.pub') }}"
with_items: USERS

- name: Copy the id_rsa.pub file to the user {{item.name}}
action: copy src=/tmp/{{item.name}}_id_rsa.pub dest=/home/{{item.name}}/.ssh/id_rsa.pub owner={{item.name}} group={{item.name}} mode=0644
with_items: USERS

- name: Copy the id_rsa file to the user {{item.name}}
action: copy src=/tmp/{{item.name}}_id_rsa dest=/home/{{item.name}}/.ssh/id_rsa owner={{item.name}} group={{item.name}} mode=0600
with_items: USERS

- template: src=utils/templates/ssh_known_hosts.conf dest=/etc/ssh/ssh_known_hosts

















