# RedHat related OSs
- name: Yum install {{ item }}
  action: yum pkg={{ item }} state=installed
  when: "ansible_os_family == 'RedHat'"
  with_items:
  - torque-server
  - torque-scheduler
  - torque-client

# Debian related OSs
- name: Apt install {{ item }}
  action: apt pkg={{ item }} state=installed update_cache=yes cache_valid_time=604800
  when: "ansible_os_family == 'Debian'"
  with_items:
  - torque-server
  - torque-scheduler
  - torque-client

- copy: content={{torque_server}} dest=/etc/torque/server_name
  notify:
   - restart {{server_service}}
   - restart {{scheduler_service}}

- template: src=hosts.conf dest={{torque_path}}/server_priv/nodes
  notify:
   - restart {{server_service}}
   - restart {{scheduler_service}}

- template: src=ssh_known_hosts.conf dest=/etc/ssh/ssh_known_hosts

- service: name={{scheduler_service}} state=started pattern=/usr/sbin/pbs_sched

- service: name={{server_service}} state=started pattern=/usr/sbin/pbs_server

- shell: echo "{{ lookup('file', 'queue.txt') }}" | qmgr

- command: /usr/sbin/create-munge-key creates=/etc/munge/munge.key
  when: "ansible_os_family == 'RedHat'"
  notify:
  - restart munge
 
- file: path=/etc/munge/munge.key owner=munge group=munge mode=0400
  when: "ansible_os_family == 'RedHat'"
  notify:
  - restart munge

